<a href="https://colab.research.google.com/github/kartik2627/python_basic/blob/main/import_and_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math

In [ ]:
math.sqrt(56)

7.483314773547883

In [ ]:
from math import sqrt , pi
math.sqrt(56)

7.483314773547883

In [ ]:
math.pi

3.141592653589793

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
import pandas as pd
a = pd.Series([1,2,3,4,5])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
b=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(b)


a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
c = pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})
print(c)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
import array as arr
a = arr.array('i',[1,2,3,4,5])
print(a)

array('i', [1, 2, 3, 4, 5])


In [ ]:
import random as rd
print(rd.randint(1,10))
print(rd.randint(1,10))
print(rd.randrange(1,10))
print(rd.choice([1,2,3,4,5]))

4
7
1
5


In [ ]:
import os
print(os.getcwd())

/content


In [ ]:
import json
data={'name ':'kartikay','age':' 21'}
json_data=json.dumps(data)
print(json_data)
print(type(json_data))
parsed_data=json.loads(json_data)
print(parsed_data)
print(type(parsed_data))

{"name ": "kartikay", "age": " 21"}
<class 'str'>
{'name ': 'kartikay', 'age': ' 21'}
<class 'dict'>


In [ ]:
import csv

with open('example.csv',mode='w',newline='') as file:
    writer=csv.writer(file)
    writer.writerow(['name','age'])
    writer.writerow(['Kartikay',21])

with open('example.csv',mode='r') as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)

['name', 'age']
['Kartikay', '21']


In [ ]:
import datetime as dt
today=dt.date.today()
print(today)
print(today.day)
print(today.month)
print(today.year)

2024-10-01
1
10
2024


In [ ]:
import time
print(time.time())
time.sleep(2)
print(time.time())

1727766501.6548004
1727766503.6635687


In [ ]:

f = open("myfile.txt", "w")
f.write("Now the file has more content!")
f.close()


In [ ]:
with open("myfile.txt", "r") as f:
    print(f.read())

Now the file has more content!


In [ ]:
with open("myfile.txt", "w") as f :
    f.write("Hello, world!")

In [ ]:
with open("myfile.txt", "r") as f:
    print(f.read())

Hello, world!


In [ ]:
with open("myfile.txt", "a") as f:
    f.write("\nNow the file has more content!")

In [ ]:
with open("myfile.txt", "r") as f:
    print(f.read())

Hello, world!
Now the file has more content!


In [ ]:
lines = ('student : ragav\n', 'student : sahil\n', 'student : ritik\n')


In [ ]:
with open("myfile.txt", "a") as f:
    f.writelines(lines)
    f.close()

In [ ]:
with open('myfile.txt', 'rb') as f:
    content = f.read()
    print(content)


b'student : ragavstudent : sahilstudent : ritikstudent : ragavstudent : sahilstudent : ritikstudent : ragavstudent : sahilstudent : ritikstudent : ragav\nstudent : sahil\nstudent : ritik\n'


In [ ]:
def count_words(filename):
    with open(filename, 'r') as f:
        content = f.read()
        words = content.split()
        return len(words)

In [ ]:
with open('newfile.txt', 'w') as f:
    f.write('This is a new file')

In [ ]:
with open('newfile.txt', 'w+') as f:
    f.write('This is a new file \n')
    f.write('This is the second line \n')
    f.write('This is the third line \n')

    f.seek(0)  # Move the file pointer to the beginning
    content = f.read()  # Read the entire content of
    print(content)

This is a new file 
This is the second line 
This is the third line 



In [ ]:
import os
new_directory = 'package'
os.mkdir(new_directory)
print(f'Directory {new_directory} created successfully')

Directory package created successfully


In [ ]:
item = os.listdir()
print(item)

['.config', 'package', 'myfile.txt', 'newfile.txt', 'sample_data']


In [ ]:
dir_name = 'package'
os.rmdir(dir_name)
print(f'Directory {dir_name} removed successfully')

Directory package removed successfully


In [ ]:
dir_name = 'Folder'
file_name = 'file.txt'
full_path = os.path.join(dir_name, file_name)
print(full_path)


Folder/file.txt


In [ ]:
import os
path = "example.txt"
if os.path.exists(path):
    print(f"{path} exists")
else:
    print(f"{path} does not exist")

example.txt does not exist


In [ ]:
def read_file(filename):
    try:
        with open('newfile.txt', 'r') as f:
            content = f.read()
            print(content)
    except FileNotFoundError:
        print(f"File '{filename}' not found")


In [ ]:
with open('file1.txt', 'w') as f:
    f.write('This is a new file/n')
    f.write('This is the second line/n')

In [ ]:
def write_file(lines,file1):
    with open(file1, 'w') as f:
        for line in lines:
            f.write(line)

In [ ]:
write_file(['Hello', 'World'], 'file1')

In [1]:
try:
  a=b
  print(a)
except:
  print("An exception occurred")

An exception occurred


In [2]:
try:
  result = 1/ 0
  print(result)
except:
  print("An exception occurred")

An exception occurred


In [3]:
try:
  result = 1/ 0
  print(result)
except ZeroDivisionError:
  print("Cannot divide by zero")

Cannot divide by zero


In [4]:
try:
  result = 1/ 0
  print(result)
except ZeroDivisionError:
  print("Cannot divide by zero")
except:
  print("An exception occurred")

Cannot divide by zero


In [5]:
try:
  num = int(input("Enter a number: "))
  result = 1/ num
  print(result)
except ValueError:
  print("Invalid input. Please enter a number")
except ZeroDivisionError:
  print("Cannot divide by zero")
except:
  print("An exception occurred")

Enter a number: 22
0.045454545454545456


In [6]:
try:
  num = int(input("Enter a number: "))
  result = 1/ num
  print(result)
except ValueError:
  print("Invalid input. Please enter a number")
except ZeroDivisionError:
  print("Cannot divide by zero")

Enter a number: 0
Cannot divide by zero


In [7]:
try:
  num = int(input("Enter a number: "))
  result = 1/ num
  print(result)
except ValueError:
  print("Invalid input. Please enter a number")
except ZeroDivisionError:
  print("Cannot divide by zero")
else:
  print("No exceptions occurred")
finally:
  print("This will always be executed")

Enter a number: 44
0.022727272727272728
No exceptions occurred
This will always be executed


In [8]:
try:
  result = 1/2
  print(result)
except:
  print("An exception occurred")
else:
  print("No exceptions occurred")
finally:
  print("This will always be executed")

0.5
No exceptions occurred
This will always be executed


In [9]:
try:
  result = 1/0
  print(result)
except:
  print("An exception occurred")
else:
  print("No exceptions occurred")
finally:
  print("This will always be executed")

An exception occurred
This will always be executed


In [10]:
if __name__ == '__main__':
    print('This program is being run by itself')
elif __name__ == 'main':
    print('This program is being imported from another module')
else:
    print('This program is being imported from another module')


This program is being run by itself


In [12]:
try:
  num = int(input("Enter a number: "))
  result = 1/ num
  print(result)
except ValueError:
  print("Invalid input. Please enter a number")
except ZeroDivisionError:
  print("Cannot divide by zero")
else:
  print("No exceptions occurred")
finally:
  print("This will always be executed")

Enter a number: 44
0.022727272727272728
No exceptions occurred
This will always be executed


In [13]:
try:
  num = int(input("Enter a number: "))
  result = 1/ num
  print(result)
except ValueError:
  print("Invalid input. Please enter a number")
except ZeroDivisionError:
  print("Cannot divide by zero")

Enter a number: 55
0.01818181818181818


In [15]:
try:
  num = int(input("Enter a number: "))
  result = 1/ num
  print(result)
except ValueError:
  print("Invalid input. Please enter a number")
except ZeroDivisionError:
  print("Cannot divide by zero")
else:
  print("No exceptions occurred")
finally:
  print("This will always be executed")

Enter a number: 657
0.0015220700152207
No exceptions occurred
This will always be executed


In [14]:
try:
  num = int(input("Enter a number: "))
  result = 1/ num
  print(result)
except ValueError:
  print("Invalid input. Please enter a number")
except ZeroDivisionError:
  print("Cannot divide by zero")

Enter a number: 0/
Invalid input. Please enter a number


In [16]:
try:
  string = str(input('enter a string'))
  print(string)
except:
  print("An exception occurred")
else:
  print("No exceptions occurred")
finally:
  print("This will always be executed")


enter a stringhiiiiii
hiiiiii
No exceptions occurred
This will always be executed


In [17]:


try:
  with open('my_new_file.txt', 'w') as f:
    f.write('This is some text.')
  with open('my_new_file.txt', 'r') as f:
    contents = f.read()
    print(contents)

except FileNotFoundError:
  print("File not found.")
except Exception as e:
  print(f"An error occurred: {e}")


This is some text.


In [18]:
try:
  file = open('my_new_file.txt', 'r')
  contents = file.read()
  print(contents)
except FileNotFoundError:
  print("File not found.")
finally:
  if 'file' in locals():
    file.close()
    print("File closed.")

This is some text.
File closed.
