<a href="https://colab.research.google.com/github/kartik2627/python_basic/blob/main/import_and_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math

In [ ]:
math.sqrt(56)

7.483314773547883

In [ ]:
from math import sqrt , pi
math.sqrt(56)

7.483314773547883

In [ ]:
math.pi

3.141592653589793

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
import pandas as pd
a = pd.Series([1,2,3,4,5])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
b=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(b)


a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
c = pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})
print(c)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
import array as arr
a = arr.array('i',[1,2,3,4,5])
print(a)

array('i', [1, 2, 3, 4, 5])


In [ ]:
import random as rd
print(rd.randint(1,10))
print(rd.randint(1,10))
print(rd.randrange(1,10))
print(rd.choice([1,2,3,4,5]))

4
7
1
5


In [ ]:
import os
print(os.getcwd())

/content


In [ ]:
import json
data={'name ':'kartikay','age':' 21'}
json_data=json.dumps(data)
print(json_data)
print(type(json_data))
parsed_data=json.loads(json_data)
print(parsed_data)
print(type(parsed_data))

{"name ": "kartikay", "age": " 21"}
<class 'str'>
{'name ': 'kartikay', 'age': ' 21'}
<class 'dict'>


In [ ]:
import csv

with open('example.csv',mode='w',newline='') as file:
    writer=csv.writer(file)
    writer.writerow(['name','age'])
    writer.writerow(['Kartikay',21])

with open('example.csv',mode='r') as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)

['name', 'age']
['Kartikay', '21']


In [ ]:
import datetime as dt
today=dt.date.today()
print(today)
print(today.day)
print(today.month)
print(today.year)

2024-10-01
1
10
2024


In [ ]:
import time
print(time.time())
time.sleep(2)
print(time.time())

1727766501.6548004
1727766503.6635687


In [3]:

f = open("myfile.txt", "w")
f.write("Now the file has more content!")
f.close()


In [4]:
with open("myfile.txt", "r") as f:
    print(f.read())

Now the file has more content!


In [6]:
with open("myfile.txt", "w") as f :
    f.write("Hello, world!")

In [7]:
with open("myfile.txt", "r") as f:
    print(f.read())

Hello, world!


In [8]:
with open("myfile.txt", "a") as f:
    f.write("\nNow the file has more content!")

In [10]:
with open("myfile.txt", "r") as f:
    print(f.read())

Hello, world!
Now the file has more content!


In [18]:
lines = ('student : ragav\n', 'student : sahil\n', 'student : ritik\n')


In [19]:
with open("myfile.txt", "a") as f:
    f.writelines(lines)
    f.close()

In [23]:
with open('myfile.txt', 'rb') as f:
    content = f.read()
    print(content)


b'student : ragavstudent : sahilstudent : ritikstudent : ragavstudent : sahilstudent : ritikstudent : ragavstudent : sahilstudent : ritikstudent : ragav\nstudent : sahil\nstudent : ritik\n'


In [21]:
def count_words(filename):
    with open(filename, 'r') as f:
        content = f.read()
        words = content.split()
        return len(words)

In [22]:
with open('newfile.txt', 'w') as f:
    f.write('This is a new file')

In [26]:
with open('newfile.txt', 'w+') as f:
    f.write('This is a new file \n')
    f.write('This is the second line \n')
    f.write('This is the third line \n')

    f.seek(0)  # Move the file pointer to the beginning
    content = f.read()  # Read the entire content of
    print(content)

This is a new file 
This is the second line 
This is the third line 



In [27]:
import os
new_directory = 'package'
os.mkdir(new_directory)
print(f'Directory {new_directory} created successfully')

Directory package created successfully


In [28]:
item = os.listdir()
print(item)

['.config', 'package', 'myfile.txt', 'newfile.txt', 'sample_data']


In [29]:
dir_name = 'package'
os.rmdir(dir_name)
print(f'Directory {dir_name} removed successfully')

Directory package removed successfully


In [30]:
dir_name = 'Folder'
file_name = 'file.txt'
full_path = os.path.join(dir_name, file_name)
print(full_path)


Folder/file.txt


In [31]:
import os
path = "example.txt"
if os.path.exists(path):
    print(f"{path} exists")
else:
    print(f"{path} does not exist")

example.txt does not exist


In [36]:
def read_file(filename):
    try:
        with open('newfile.txt', 'r') as f:
            content = f.read()
            print(content)
    except FileNotFoundError:
        print(f"File '{filename}' not found")


In [37]:
with open('file1.txt', 'w') as f:
    f.write('This is a new file/n')
    f.write('This is the second line/n')

In [42]:
def write_file(lines,file1):
    with open(file1, 'w') as f:
        for line in lines:
            f.write(line)

In [43]:
write_file(['Hello', 'World'], 'file1')