<a href="https://colab.research.google.com/github/kartik2627/python_basic/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
data = np.array([[1.2,3,6],[0,4,6]])
data

array([[1.2, 3. , 6. ],
       [0. , 4. , 6. ]])

In [2]:
data*10

array([[12., 30., 60.],
       [ 0., 40., 60.]])

In [3]:
data+data1

array([[ 2.4,  6. , 12. ],
       [ 0. ,  8. , 12. ]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

In [7]:
data1=[6,7.2,5.6,4,1]
arr1 = np.array(data1)
arr1

array([6. , 7.2, 5.6, 4. , 1. ])

In [8]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim

2

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int64')

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.empty((2,3,2))

array([[[9.79828973e-316, 0.00000000e+000],
        [6.79544108e-310, 5.75600311e-317],
        [6.79544148e-310, 6.79548689e-310]],

       [[5.75746950e-317, 6.79548689e-310],
        [6.79548689e-310, 5.75818095e-317],
        [5.75697148e-317, 6.79544148e-310]]])

In [16]:
np.ndim

<function ndim at 0x7d1805f205b0>

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
arr1 = np.array([1,2,3,4],dtype=np.float64)
arr2 = np.array([1,2,3,4],dtype=np.int32)

In [19]:
arr1

array([1., 2., 3., 4.])

In [20]:
arr2

array([1, 2, 3, 4], dtype=int32)

In [21]:
arr1.dtype

dtype('float64')

In [23]:
arr = np.array([1,2,3,4,5])
np.dtype
arr.dtype

dtype('int64')

In [24]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([3.4,4,2.8,0.4,3,8])
arr

array([3.4, 4. , 2.8, 0.4, 3. , 8. ])

In [27]:
arr.astype(np.int64)

array([3, 4, 2, 0, 3, 8])

In [31]:
num_string = np.array(['1.5','34','8.9','23','12','98'],dtype=np.bytes_)
num_string

array([b'1.5', b'34', b'8.9', b'23', b'12', b'98'], dtype='|S3')

In [32]:
num_string.astype(float)
num_string

array([b'1.5', b'34', b'8.9', b'23', b'12', b'98'], dtype='|S3')

In [33]:
int_array = np.arange(10)

In [34]:
calibers = np.array([.22,.270,.356,.45,.34],dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [38]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [39]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [40]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [41]:
arr2 = np.array([[0,4,1],[7,2,12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [43]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [44]:
array = np.arange(10)
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
array[5:9]

array([5, 6, 7, 8])

In [46]:
arr[5:8]=12
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
array[5:8] =12
array

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [48]:
arr_slice = array[5:8]
arr_slice

array([12, 12, 12])

In [49]:
array[1] =12345
array

array([    0, 12345,     2,     3,     4,    12,    12,    12,     8,
           9])

In [50]:
arr_slice[:]=64
arr_slice

array([64, 64, 64])

In [51]:
arr2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [52]:
arr2d[2]

array([11, 12, 13, 14, 15])

In [53]:
arr2d[1][2]

np.int64(8)

In [54]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
odd_values = arr3d[0].copy()

In [57]:
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr[1:6]

array([[4, 5, 6]])

In [61]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [62]:
arr2d[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
arr2d[:2,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [64]:
arr2d[:2,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [65]:
arr2d[:,:1]

array([[ 1],
       [ 6],
       [11]])

In [66]:
arr2d[:2,3]=0
arr2d

array([[ 1,  2,  3,  0,  5],
       [ 6,  7,  8,  0, 10],
       [11, 12, 13, 14, 15]])

In [67]:
name =np.array(["kartikay","annanya","chinmey","ankit","neha","ritik","ankit","kartikay"])
name

array(['kartikay', 'annanya', 'chinmey', 'ankit', 'neha', 'ritik',
       'ankit', 'kartikay'], dtype='<U8')

In [68]:
data=np.array([[1,2],[1,3],[2,3],[3,4],[3,9],[3,1],[1,6],[2,9]])
data

array([[1, 2],
       [1, 3],
       [2, 3],
       [3, 4],
       [3, 9],
       [3, 1],
       [1, 6],
       [2, 9]])

In [69]:
name == "kartikay"

array([ True, False, False, False, False, False, False,  True])

In [70]:
data[name=="kartikay"]

array([[1, 2],
       [2, 9]])

In [71]:
name != "kartikay"

array([False,  True,  True,  True,  True,  True,  True, False])

In [73]:
~(name == "kartikay")

array([False,  True,  True,  True,  True,  True,  True, False])

In [74]:
data[~(name=="kartikay")]

array([[1, 3],
       [2, 3],
       [3, 4],
       [3, 9],
       [3, 1],
       [1, 6]])

In [75]:
mask =((name=="kartikay")|(name=="ankit"))
mask

array([ True, False, False,  True, False, False,  True,  True])

In [76]:
data[mask]

array([[1, 2],
       [3, 4],
       [1, 6],
       [2, 9]])

In [77]:
data[data<0]=0
data

array([[1, 2],
       [1, 3],
       [2, 3],
       [3, 4],
       [3, 9],
       [3, 1],
       [1, 6],
       [2, 9]])

In [78]:
arr = np.zeros((8,4))

In [79]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
for i in range(8):
  arr[i]=i

In [81]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [82]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [83]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [85]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

In [86]:
arr[[1,5,7,2],[0,3,1,2]]

array([1., 5., 7., 2.])

In [90]:
arr=np.arange(15).reshape((3,5))

In [91]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [89]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [92]:
arr=np.array([[0,1,0],[2,3,5],[6,4,5],[34,7,9],[2,5,8]])

In [93]:
arr

array([[ 0,  1,  0],
       [ 2,  3,  5],
       [ 6,  4,  5],
       [34,  7,  9],
       [ 2,  5,  8]])

In [94]:
np.dot(arr.T,arr)

array([[1200,  278,  362],
       [ 278,  100,  138],
       [ 362,  138,  195]])

In [95]:
arr.T @ arr

array([[1200,  278,  362],
       [ 278,  100,  138],
       [ 362,  138,  195]])

In [96]:
arr

array([[ 0,  1,  0],
       [ 2,  3,  5],
       [ 6,  4,  5],
       [34,  7,  9],
       [ 2,  5,  8]])

In [97]:
arr.swapaxes(0,1)

array([[ 0,  2,  6, 34,  2],
       [ 1,  3,  4,  7,  5],
       [ 0,  5,  5,  9,  8]])

In [98]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[-1.28242142,  0.88733623,  0.59283193,  1.91493654],
       [-0.87644873,  0.69593705,  0.66027048,  1.36194066],
       [-0.15404361,  0.32009366, -1.87844714,  1.34420095],
       [ 1.24528428, -0.23801502, -0.9800044 ,  0.11551295]])

In [99]:
arr =np.arange(10)

In [100]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [102]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [104]:
rng = np.random.default_rng()
x = rng.standard_normal(8)

In [105]:
y = rng.standard_normal(8)

In [106]:
x

array([ 0.22168665,  0.9872435 , -0.39391725, -0.26787295, -1.85937991,
        1.85777325, -0.73012654,  2.7025899 ])

In [107]:
y

array([-0.99125622, -0.11201074, -0.47223982,  1.63015232,  0.45036489,
        0.40023875, -1.60898938, -0.26298946])

In [108]:
np.maximum(x,y)

array([ 0.22168665,  0.9872435 , -0.39391725,  1.63015232,  0.45036489,
        1.85777325, -0.73012654,  2.7025899 ])

In [109]:
arr = rng.standard_normal(7)*5

In [110]:
arr

array([-0.99507036, -8.7961184 ,  3.6725364 , -1.78490128,  7.16892856,
        1.34739541, -1.34592162])

In [111]:
remainder,whole_part = np.modf(arr)

In [112]:
remainder

array([-0.99507036, -0.7961184 ,  0.6725364 , -0.78490128,  0.16892856,
        0.34739541, -0.34592162])

In [113]:
whole_part

array([-0., -8.,  3., -1.,  7.,  1., -1.])

In [114]:
arr

array([-0.99507036, -8.7961184 ,  3.6725364 , -1.78490128,  7.16892856,
        1.34739541, -1.34592162])