<a href="https://colab.research.google.com/github/kartik2627/python_basic/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
- Short for Numerical Python
- Foundational Package for Numerical computing in python
- Provides an ndarray object which is an efficient multidimensional array providing fast array oriented operations
- Provides a lot of functions

In [ ]:
import numpy as np

# Creating ndarrays

##### Creating ndarray from an object

In [ ]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
t1 = (1,2,3,4,5)
a1 = np.array(t1)
a1

array([1, 2, 3, 4, 5])

In [ ]:
a1 = np.array(range(1,11))
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a1.shape

(10,)

In [ ]:
a1.dtype

dtype('int32')

In [ ]:
a1.ndim

1

In [ ]:
a1 = np.array([[1,2,3], [4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a1.shape

(2, 3)

In [ ]:
a1.ndim

2

In [ ]:
a1 = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
a1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a1.shape

(2, 2, 2)

In [ ]:
a1.ndim

3

In [ ]:
a = np.array([1,2,3,4,5], dtype = float)
a

array([1., 2., 3., 4., 5.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a = np.array([1.5,2.6,3.1,4.8,5.2], dtype = int)
a

array([1, 2, 3, 4, 5])

In [ ]:
a.dtype

dtype('int32')

### Typecasting ndarrays

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a = a.astype(float)
a

array([1., 2., 3., 4., 5.])

In [ ]:
a = a.astype(int)
a

array([1, 2, 3, 4, 5])

### Creating ndarrays by specifying a range

In [ ]:
a1 = np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.arange(0,21,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
a1 = np.arange(10)       # (0,10,1)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.arange(10, dtype = float)
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Creating ndarrays of ones

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones((5,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Creating ndarray of zeros

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Creating ndarray of a specific value

In [ ]:
np.full((4,5), fill_value = 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### Creating an identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# --------------------------------------------------------------------------------------
# Operations on ndarrays

In [ ]:
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [ ]:
# list
l = [1,2,3,4,5,6]
l + 2

TypeError: can only concatenate list (not "int") to list

In [ ]:
a1 + 2

array([3, 4, 5, 6, 7, 8])

In [ ]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,9]
l1 + l2         # concatenation

[1, 2, 3, 4, 5, 6, 7, 8, 9, 9]

In [ ]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([4,5,6,7,8,9])

In [ ]:
a1 + a2

array([ 5,  7,  9, 11, 13, 15])

In [ ]:
a1 + [2,3,4,5,6,7]

array([ 3,  5,  7,  9, 11, 13])

In [ ]:
a1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
print(a1)
print(a2)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [ ]:
a1 * a2

array([ 4, 10, 18, 28, 40, 54])

In [ ]:
a1 = np.array([2,4,6,8,10])
a1 / 2

array([1., 2., 3., 4., 5.])

In [ ]:
a1 // 2

array([1, 2, 3, 4, 5], dtype=int32)

In [ ]:
a1 % 3

array([2, 1, 0, 2, 1], dtype=int32)

In [ ]:
a1 ** 2

array([  4,  16,  36,  64, 100])

In [ ]:
a2 = np.array([2,3,4,5,6])
a1 ** a2

array([      4,      64,    1296,   32768, 1000000], dtype=int32)

In [ ]:
a1

array([ 2,  4,  6,  8, 10])

In [ ]:
2 / a1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [ ]:
l1 = [1,2,3,4,5,6]
l1 < 4

TypeError: '<' not supported between instances of 'list' and 'int'

In [ ]:
a1 = np.array([1,2,3,4,5,6])
a1 < 4

array([ True,  True,  True, False, False, False])

In [ ]:
# list
l1 = [5,1,4,5,3,6]
l2 = [7,4,2,1,6,7]
l1 < l2

True

In [ ]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,7])

In [ ]:
a1 < a2

array([ True,  True, False, False,  True,  True])

In [ ]:
a1 > a2

array([False, False,  True,  True, False, False])

In [ ]:
a1 <= a2

array([ True,  True, False, False,  True,  True])

In [ ]:
a1 == a2

array([False, False, False, False, False, False])

In [ ]:
# Operation between two ndarrays is not possible if shapes are not same
a1 = np.array([1,2,3,4,5])
a2 = np.array([2,3,4,5,6,7])

a1 + a2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

## Indexing and Slicing ndarrays

In [ ]:
a = np.arange(11,21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
a[0]

11

In [ ]:
a[1]

12

In [ ]:
a[6]

17

In [ ]:
a[-1]

20

In [ ]:
a[-2]

19

In [ ]:
a[0:8]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
a[::]          # By default start = 0, end = len(a), step = 1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
a[-8:-3]

array([13, 14, 15, 16, 17])

In [ ]:
a[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

## Reshape and Transpose

In [ ]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.shape

(16,)

In [ ]:
a.ndim

1

In [ ]:
a = a.reshape((16,1))
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [ ]:
a.shape

(16, 1)

In [ ]:
a.ndim

2

In [ ]:
a = a.reshape((1,16))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.shape

(1, 16)

In [ ]:
a.ndim

2

In [ ]:
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
a = np.arange(36)
a.reshape((1,36))
a.reshape((2,18))
a.reshape((3,12))
a.reshape((4,9))
a.reshape((6,6))
a.reshape((9,4))
a.reshape((12,3))
a.reshape((18,2))
a.reshape((36,1))
print('Total possible 2d shapes : ', 9)

Total possible 2d shapes :  9


In [ ]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

# ----------------------------------------------------------------------------------

# Functions

In [ ]:
a = np.array([2,4,3,6,5,8,7,9,1,0])
a

array([2, 4, 3, 6, 5, 8, 7, 9, 1, 0])

In [ ]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
s = np.square(a)
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.sqrt(s)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a = np.array([8,27,64])
np.cbrt(a)

array([2., 3., 4.])

In [ ]:
np.abs([-1,2,3,-5,-6,-2,6])

array([1, 2, 3, 5, 6, 2, 6])

In [ ]:
np.add([1,2,3],[4,5,6])

array([5, 7, 9])

In [ ]:
np.subtract([4,5,6],[1,2,3])

array([3, 3, 3])

In [ ]:
np.multiply([1,2,3],[2,3,4])

array([ 2,  6, 12])

In [ ]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,5])

In [ ]:
np.maximum(a1,a2)

array([3, 4, 4, 5, 6, 6])

In [ ]:
np.minimum(a1,a2)

array([2, 1, 2, 1, 3, 5])

In [ ]:
np.greater(a1,a2)

array([False, False,  True,  True, False,  True])

In [ ]:
np.less(a1,a2)

array([ True,  True, False, False,  True, False])

In [ ]:
a1 = np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
np.mean([1,2,3,4,5,6,7,8,9])

5.0

In [ ]:
np.var([1,2,3,4,5,6,7,8,9])

6.666666666666667

In [ ]:
np.std([1,2,3,4,5,6,7,8,9])

2.581988897471611

In [ ]:
np.median(a1)

10.0

In [ ]:
a1.mean()

10.0

In [ ]:
a1.var()

36.666666666666664

In [ ]:
a1.std()

6.0553007081949835

In [ ]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [ ]:
a.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [ ]:
a.min()

1

In [ ]:
a.max()

10

In [ ]:
a.sum()

55

In [ ]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
a.shape

(8, 8)

In [ ]:
a.mean()

31.5

In [ ]:
a.mean(axis = 0)

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [ ]:
a.mean(axis = 1)

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [ ]:
a.std()

18.472953201911167

In [ ]:
a.std(axis = 0)

array([18.33030278, 18.33030278, 18.33030278, 18.33030278, 18.33030278,
       18.33030278, 18.33030278, 18.33030278])

In [ ]:
a.std(axis = 1)

array([2.29128785, 2.29128785, 2.29128785, 2.29128785, 2.29128785,
       2.29128785, 2.29128785, 2.29128785])

In [ ]:
a.max()

63

In [ ]:
a.max(axis = 0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
a.max(axis = 1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [ ]:
# For a specific row
a[3].mean()

27.5

In [ ]:
# For a specific column
a[:,0].mean()

28.0

In [ ]:
x = np.array([10,30,80,20,40])
x

array([10, 30, 80, 20, 40])

In [ ]:
np.argmax(x)

2

In [ ]:
np.argmin(x)

0

In [ ]:
a1 = np.array([2,1,5,4,3,5,6,7,3,10,2,3]).reshape(3,4)
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [ ]:
np.argmax(a1)

9

In [ ]:
np.argmax(a1, axis = 0)

array([1, 2, 1, 1], dtype=int64)

In [ ]:
np.argmax(a1, axis = 1)

array([2, 3, 1], dtype=int64)

In [ ]:
np.argmin(a1, axis = 0)

array([0, 0, 2, 2], dtype=int64)

In [ ]:
np.argmin(a1, axis = 1)

array([1, 0, 2], dtype=int64)

In [ ]:
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [ ]:
a1.ravel()

array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [ ]:
a2 = a1.reshape(1,3,4)
a2

array([[[ 2,  1,  5,  4],
        [ 3,  5,  6,  7],
        [ 3, 10,  2,  3]]])

In [ ]:
a2.shape

(1, 3, 4)

In [ ]:
a2 = a2.squeeze()
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [ ]:
a2.shape

(3, 4)

In [ ]:
a2 = a2.reshape(3,4,1)
a2

array([[[ 2],
        [ 1],
        [ 5],
        [ 4]],

       [[ 3],
        [ 5],
        [ 6],
        [ 7]],

       [[ 3],
        [10],
        [ 2],
        [ 3]]])

In [ ]:
a2 = a2.squeeze()
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [ ]:
a2.shape

(3, 4)

In [ ]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Determinant and Inverse

In [ ]:
from numpy.linalg import det, inv, eig
a = np.array([4,3,7,9,2,3,9,6,1,4,7,6,11,4,8,7]).reshape((4,4))
a

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7]])

In [ ]:
det(a)

527.0000000000006

In [ ]:
inv(a)

array([[-0.0170778 , -0.02087287, -0.07969639,  0.10815939],
       [-0.22580645, -0.38709677,  0.61290323,  0.09677419],
       [-0.10436433,  0.31688805, -0.15370019, -0.0056926 ],
       [ 0.27514231, -0.10815939, -0.04933586, -0.07590133]])

In [ ]:
eig(a)

(array([22.97864964,  3.76499269, -4.34011564, -1.40352668]),
 array([[-0.51289911, -0.39468612,  0.5270535 ,  0.05108621],
        [-0.41676444,  0.52758299,  0.07812217, -0.85784205],
        [-0.37954612,  0.5045306 ,  0.33673147,  0.494701  ],
        [-0.64744625, -0.55796767, -0.77635266, -0.12949184]]))

### Concatenation

In [ ]:
a1 = np.arange(6)
a2 = np.arange(6,12)

In [ ]:
np.concatenate((a1,a2))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a1 = a1.reshape(2,3)
a2 = a2.reshape(2,3)
print(a1)
print(a2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((a1,a2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((a1,a2), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((a1,a2), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
a1 = a
a2 = a.T
print(a1)
print()
print(a2)

[[ 4  3  7  9]
 [ 2  3  9  6]
 [ 1  4  7  6]
 [11  4  8  7]]

[[ 4  2  1 11]
 [ 3  3  4  4]
 [ 7  9  7  8]
 [ 9  6  6  7]]


In [ ]:
np.concatenate((a1,a2), axis = 0)

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7],
       [ 4,  2,  1, 11],
       [ 3,  3,  4,  4],
       [ 7,  9,  7,  8],
       [ 9,  6,  6,  7]])

In [ ]:
np.concatenate((a1,a2), axis = 1)

array([[ 4,  3,  7,  9,  4,  2,  1, 11],
       [ 2,  3,  9,  6,  3,  3,  4,  4],
       [ 1,  4,  7,  6,  7,  9,  7,  8],
       [11,  4,  8,  7,  9,  6,  6,  7]])

# Random numbers

In [ ]:
np.random.randint(1,10)

9

In [ ]:
np.random.randint(50)

3

In [ ]:
np.random.randint(1,100,10)

array([94, 17, 81, 24, 44, 66, 27, 14, 84, 36])

In [ ]:
np.random.randint(11,100,(10,10))

array([[42, 60, 58, 43, 65, 34, 20, 72, 57, 56],
       [68, 89, 98, 70, 65, 95, 18, 37, 11, 99],
       [81, 12, 71, 83, 62, 43, 74, 20, 33, 60],
       [48, 67, 65, 86, 86, 39, 65, 55, 84, 75],
       [36, 34, 73, 78, 99, 73, 33, 47, 30, 84],
       [41, 44, 79, 78, 57, 52, 24, 74, 34, 90],
       [78, 31, 21, 86, 66, 98, 66, 79, 44, 70],
       [84, 70, 14, 80, 21, 13, 64, 80, 49, 74],
       [85, 25, 70, 97, 39, 81, 70, 85, 28, 32],
       [73, 73, 43, 89, 41, 33, 40, 60, 82, 97]])

In [ ]:
np.random.rand(10)

array([1.76814114e-01, 7.39295657e-01, 2.19638173e-01, 6.10844819e-01,
       1.12657851e-01, 5.96218820e-01, 3.00841592e-04, 1.61929926e-01,
       1.85025322e-01, 9.49693806e-01])

In [ ]:
np.random.randn(10)

array([ 0.53311173,  1.51772831,  0.15965479, -0.64174755,  0.68166702,
        1.60969144, -0.26903086, -0.36577269,  0.30886807,  0.10466335])

In [ ]:
np.random.randn(3,4)

array([[ 0.26637228, -1.38833156,  0.23230733, -2.1458538 ],
       [-0.97378295,  2.1201828 ,  0.05121573,  0.80329421],
       [ 1.02198845,  1.21912687, -0.34324688, -0.16104361]])

# Conditional Indexing

In [ ]:
a = np.random.randint(11,100,(8,8))
a

array([[97, 68, 73, 35, 62, 32, 98, 66],
       [19, 14, 52, 25, 93, 20, 76, 26],
       [56, 38, 37, 45, 88, 88, 22, 35],
       [96, 56, 77, 53, 44, 25, 89, 42],
       [69, 81, 13, 49, 72, 73, 79, 27],
       [78, 20, 73, 46, 27, 60, 60, 36],
       [59, 86, 41, 37, 89, 94, 27, 29],
       [67, 92, 52, 35, 60, 86, 98, 91]])

In [ ]:
a > 50

array([[ True,  True,  True, False,  True, False,  True,  True],
       [False, False,  True, False,  True, False,  True, False],
       [ True, False, False, False,  True,  True, False, False],
       [ True,  True,  True,  True, False, False,  True, False],
       [ True,  True, False, False,  True,  True,  True, False],
       [ True, False,  True, False, False,  True,  True, False],
       [ True,  True, False, False,  True,  True, False, False],
       [ True,  True,  True, False,  True,  True,  True,  True]])

In [ ]:
a[a > 50]

array([97, 68, 73, 62, 98, 66, 52, 93, 76, 56, 88, 88, 96, 56, 77, 53, 89,
       69, 81, 72, 73, 79, 78, 73, 60, 60, 59, 86, 89, 94, 67, 92, 52, 60,
       86, 98, 91])

In [ ]:
a[a < 50]

array([35, 32, 19, 14, 25, 20, 26, 38, 37, 45, 22, 35, 44, 25, 42, 13, 49,
       27, 20, 46, 27, 36, 41, 37, 27, 29, 35])

In [ ]:
a[a <= 40]

array([35, 32, 19, 14, 25, 20, 26, 38, 37, 22, 35, 25, 13, 27, 20, 27, 36,
       37, 27, 29, 35])

In [ ]:
a[a == 20]

array([20, 20])

# Slicing in Multidimensional Arrays

In [ ]:
a = np.random.randint(10,100,(10,10))
a

array([[71, 77, 81, 98, 26, 45, 20, 33, 52, 62],
       [48, 77, 72, 40, 50, 80, 44, 18, 94, 90],
       [99, 89, 95, 56, 81, 26, 94, 90, 66, 97],
       [32, 89, 33, 98, 14, 58, 27, 97, 56, 59],
       [19, 11, 14, 11, 62, 67, 34, 49, 30, 65],
       [80, 78, 42, 62, 12, 92, 33, 75, 27, 47],
       [97, 93, 98, 40, 53, 87, 28, 65, 54, 44],
       [86, 71, 53, 61, 63, 70, 88, 29, 41, 98],
       [62, 71, 23, 43, 95, 69, 49, 94, 82, 91],
       [44, 80, 93, 27, 73, 11, 41, 90, 95, 93]])

In [ ]:
a[0]

array([71, 77, 81, 98, 26, 45, 20, 33, 52, 62])

In [ ]:
a[0:5]

array([[71, 77, 81, 98, 26, 45, 20, 33, 52, 62],
       [48, 77, 72, 40, 50, 80, 44, 18, 94, 90],
       [99, 89, 95, 56, 81, 26, 94, 90, 66, 97],
       [32, 89, 33, 98, 14, 58, 27, 97, 56, 59],
       [19, 11, 14, 11, 62, 67, 34, 49, 30, 65]])

In [ ]:
a[0:5 , 0:4]

array([[71, 77, 81, 98],
       [48, 77, 72, 40],
       [99, 89, 95, 56],
       [32, 89, 33, 98],
       [19, 11, 14, 11]])

In [ ]:
a[0:6, 3:8]

array([[98, 26, 45, 20, 33],
       [40, 50, 80, 44, 18],
       [56, 81, 26, 94, 90],
       [98, 14, 58, 27, 97],
       [11, 62, 67, 34, 49],
       [62, 12, 92, 33, 75]])