<a href="https://colab.research.google.com/github/kartik2627/python_basic/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
arr1 = np.array([4,5,6,7,8],dtype=int)

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr0=np.array(0)
print(arr0,arr0.shape)
arr1=np.array([1,2,3,4,5])
print(arr1,arr1.shape)
arr2=np.array([[0,1,2],[3,4,5]])
print(arr2,arr2.shape)
arr3=np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(arr3,arr3.shape)
arr4=np.array([[[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]])
print(arr4,arr4.shape)

0 ()
[1 2 3 4 5] (5,)
[[0 1 2]
 [3 4 5]] (2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]] (1, 2, 2, 3)


In [ ]:
arr0=np.array(0)
print(arr0,arr0.shape,arr0.ndim)
arr1=np.array([1,2,3,4,5])
print(arr1,arr1.shape,arr1.ndim)
arr2=np.array([[0,1,2],[3,4,5]])
print(arr2,arr2.shape,arr2.ndim)
arr3=np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(arr3,arr3.shape)
arr4=np.array([[[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]])
print(arr4,arr4.shape)

In [ ]:
identity_matrix = np.identity(2)
print(identity_matrix)

[[1. 0.]
 [0. 1.]]


In [ ]:
id2 = np.identity(2, dtype=int)
print(id2)

id3 = np.identity(3, dtype=int)
print(id3)

id4 = np.identity(4, dtype=int)
print(id4)

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
arr2 =np.eye(2)
print(arr2)
arr3 =np.eye(3)
print(arr3)
arr4 =np.eye(4)
print(arr4)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.zeros((2,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr5 = np.full((3,5),5)
print(arr5)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
arr = [[5 for _ in range(5)] for _ in range(3)]
print(arr)

[[5, 5, 5, 5, 5], [5, 5, 5, 5, 5], [5, 5, 5, 5, 5]]


In [ ]:
np.ones((3,5))*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [ ]:
np.random.randint(0,100,size=25)

array([26, 60, 47, 70, 78, 64, 50, 83, 81,  7, 70, 67, 26, 60, 65, 54, 14,
       65, 93, 98, 36, 81, 22, 49, 35])

In [ ]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data_list = [0, 1, 2, 3, 4]
data_tuple = (5, 6, 7, 8, 9)
data_set = {10, 2, 1, 0}
a = pd.Series(data_list)
b = pd.Series(data_tuple)

print(a)
print(b)


0    0
1    1
2    2
3    3
4    4
dtype: int64
0    5
1    6
2    7
3    8
4    9
dtype: int64


In [ ]:
c = list( data_set)
c = pd.Series(c)
print(c)

0     0
1     1
2    10
3     2
dtype: int64


In [ ]:
people = {
    "Kartikay": "sood",
    "sahil": "sharma",
    "Kritika": "Thakur"
}

series = pd.Series(people ,dtype= str)
print(series)



Kartikay      sood
sahil       sharma
Kritika     Thakur
dtype: object


In [ ]:
series = pd.Series(range(11), index=range(11))
data_list = series.tolist()
print("List:", data_list)
data_dict = series.to_dict()
print("Dictionary:", data_dict)
data_tuple = tuple(series.values)
print("Tuple:", data_tuple)
data_set = set(series.values)
print("Set:", data_set)

List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Dictionary: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10}
Tuple: (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
Set: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
x = 10

series = pd.Series(range(x))
print(series.head(5))
print(series.tail(5))
series.loc[4] = 50
print(series)
series.iloc[-1] = 100

series = series.iloc[1:]

print(series)

0    0
1    1
2    2
3    3
4    4
dtype: int64
5    5
6    6
7    7
8    8
9    9
dtype: int64
0     0
1     1
2     2
3     3
4    50
5     5
6     6
7     7
8     8
9     9
dtype: int64
1      1
2      2
3      3
4     50
5      5
6      6
7      7
8      8
9    100
dtype: int64


In [1]:

import numpy as np

In [2]:
data = np.array([1,2,3,4,5,6])
print(data)

[1 2 3 4 5 6]


In [3]:
np.mean(data)

3.5

In [4]:
np.var(data)

2.9166666666666665

In [5]:
np.std(data)

1.707825127659933

In [6]:
l1 = [1,2,3,4,5,6]
a1 = np.array(l1)
print(a1)

[1 2 3 4 5 6]


In [7]:
type(a1)

numpy.ndarray

In [8]:
t1 = (1,2,3,4,5,6)
a2 = np.array(t1)
print(a2)

[1 2 3 4 5 6]


In [9]:
a = np.array(range(1,11))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
type(a)

numpy.ndarray

In [11]:
a.shape

(10,)

In [13]:
a.ndim

1

In [14]:
a.dtype

dtype('int64')

In [15]:
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a1.ndim

2

In [18]:
a1.shape

(2, 3)

In [19]:
a2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
a2.shape

(2, 2, 3)

In [21]:
a.ndim

1

In [22]:
a3 = np.array([1,2,3,4,5],dtype=float)
a3

array([1., 2., 3., 4., 5.])

In [23]:
a3 = a3.astype(int)
a3

array([1, 2, 3, 4, 5])

In [24]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr = np.arange(0,11,2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [27]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
np.full((4,6),fill_value = 6)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [33]:
np.full((3,3),fill_value = 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [34]:
l1 =[1,2,3,4,5]
l2 =[6,7,8,9,10]
l1 + l2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [35]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1 + a2

array([ 7,  9, 11, 13, 15])

In [36]:
a1 * 3

array([ 3,  6,  9, 12, 15])

In [37]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [38]:
a1 // 2

array([0, 1, 1, 2, 2])

In [39]:
a1%3

array([1, 2, 0, 1, 2])

In [40]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[0]

0

In [42]:
a[1]

1

In [43]:
a[2:6]

array([2, 3, 4, 5])

In [44]:
a[-3]

7

In [45]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a[2:6:2]

array([2, 4])

In [47]:
a[-8:-2]

array([2, 3, 4, 5, 6, 7])

In [48]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
a.shape

(16,)

In [50]:
a.ndim

1

In [51]:
a = a.reshape((16,1))
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [52]:
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
a.reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [54]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
np.concatenate([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
a.sort()
a

array([1, 2, 3, 4, 5])

In [56]:
s=np.square(a)
s

array([ 1,  4,  9, 16, 25])