<a href="https://colab.research.google.com/github/kartik2627/python_basic/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=100
def myfunc(b):
  print(b)
  b=101
  print(b)
myfunc(a)

100
101


In [ ]:
###pass by reference
c = [10,20,30]
def changethem(d):
  print(d)
  d[0]=99
  d[1]=100
  print(d)
changethem(c)

[10, 20, 30]
[99, 100, 30]


In [ ]:
x = lambda a:a+10
print(x(10))

20


In [ ]:
z = lambda x,y:x*y
print(z(10,29))

290


In [ ]:
def myfun(n):
  return lambda a:a*n

In [ ]:
doubleme = myfun(3)
print(doubleme(12))

36


In [ ]:
#numpy

In [ ]:
import numpy as np
a= np.array([1,2,3])
print(a)
b= np.array([[1,2,3],[1,2,3]])
print(b)

[1 2 3]
[[1 2 3]
 [1 2 3]]


In [ ]:
c =np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
d = np.arange(1,10,2)
print(d)

[1 3 5 7 9]


In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [ ]:
np.full((4,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [ ]:
np.random.random((2,3))

array([[0.14237484, 0.45553282, 0.81945297],
       [0.27200336, 0.13702244, 0.29752493]])

In [ ]:
np.random.random((3,3))

array([[0.57275334, 0.44330594, 0.8177754 ],
       [0.54877514, 0.2543418 , 0.33245912],
       [0.63053055, 0.59877697, 0.92276639]])

In [ ]:
#numpy array inspection
#checking the size of array

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print (a.shape)

(2, 3)


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b.shape = (3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b.shape = (3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.array([[1,2,3,4,5],[5,6,7,8,9]])
a.shape = (10,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
print(a.ndim)

1


In [ ]:
b=a.reshape(2,3,4)
print(b.ndim)

3


In [ ]:
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


# find number of element in array

In [ ]:
print(a.size)

24


In [ ]:
print(b.size)

24


In [ ]:
# data type of array

In [ ]:
import numpy as np

In [ ]:
a = np.arange(24,dtype=float)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


In [ ]:
np.sum([10,20])

30

In [1]:
import numpy as np

In [2]:
#sum function
a, b = 10,20
np.sum([a,b])

30

In [4]:
np.sum([[1,2],[4,5]],axis=0)

array([5, 7])

In [5]:
np.sum([[1,2],[4,5]],axis=1)

array([3, 9])

In [6]:
np.subtract(30,10)

20

In [7]:
np.multiply(23,8)

184

In [9]:
np.divide(123,3)

41.0

In [10]:
a=np.array([2,4,6])
b=np.array([3,5,7])
np.multiply(a,b)

array([ 6, 20, 42])

In [12]:
np.sqrt(a)
np.exp(a)
np.sin(a)
np.cos(a)

array([-0.41614684, -0.65364362,  0.96017029])

In [13]:
import numpy as np

In [14]:
a=np.array([1,3,5,7,9])
b=np.array([2,4,6,8,0])
np.np.cconcatenate((a,b))

array([1, 3, 5, 7, 9, 2, 4, 6, 8, 0])

In [15]:
np.hstack((a,b))

array([1, 3, 5, 7, 9, 2, 4, 6, 8, 0])

In [16]:
np.vstack((a,b))

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0]])

In [17]:
np.column_stack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [18]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [20]:
print(np.hsplit(x,2))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [22]:
print(np.vsplit(x,2))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
